In [1]:
# Import Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
eeg_data = pd.read_csv("data.csv")

In [3]:
eeg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Columns: 180 entries, Signal to y
dtypes: int64(179), object(1)
memory usage: 15.8+ MB


In [4]:
eeg_data.head()

Signal   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  4  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  5  
3   -80   -77   -85   -77   -72   -69   -65  5  
4   -12   -32   -41   -65   -83   -89   -73  5  

[5 rows x 180 columns]

In [5]:
# Check the lables of the Class
eeg_data['y'].unique()

array([4, 1, 5, 2, 3])

In [6]:
# Convert the 5 classes into binary class
def convert_binary_class(y):
    if y == 2 or y == 3 or y == 4 or y == 5 :
        return 0
    else :
        return 1

In [7]:
# Apply above function to convert into binary class
eeg_data['y'] = eeg_data['y'].apply(convert_binary_class)

In [8]:
eeg_data.head()

Signal   X1   X2   X3   X4   X5   X6   X7   X8   X9 ...  X170  X171  \
0  X21.V1.791  135  190  229  223  192  125   55   -9  -33 ...   -17   -15   
1  X15.V1.924  386  382  356  331  320  315  307  272  244 ...   164   150   
2     X8.V1.1  -32  -39  -47  -37  -32  -36  -57  -73  -85 ...    57    64   
3   X16.V1.60 -105 -101  -96  -92  -89  -95 -102 -100  -87 ...   -82   -81   
4   X20.V1.54   -9  -65  -98 -102  -78  -48  -16    0  -21 ...     4     2   

   X172  X173  X174  X175  X176  X177  X178  y  
0   -31   -77  -103  -127  -116   -83   -51  0  
1   146   152   157   156   154   143   129  1  
2    48    19   -12   -30   -35   -35   -36  0  
3   -80   -77   -85   -77   -72   -69   -65  0  
4   -12   -32   -41   -65   -83   -89   -73  0  

[5 rows x 180 columns]

In [9]:
# Remove unnecessory columns that is the name of the signal
del eeg_data['Signal']

In [11]:
eeg_data.head(1)

X1   X2   X3   X4   X5   X6  X7  X8  X9  X10 ...  X170  X171  X172  X173  \
0  135  190  229  223  192  125  55  -9 -33  -38 ...   -17   -15   -31   -77   

   X174  X175  X176  X177  X178  y  
0  -103  -127  -116   -83   -51  0  

[1 rows x 179 columns]

## Train Test Split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(eeg_data.drop('y',axis=1), 
                                                    eeg_data['y'], test_size=0.30, 
                                                    random_state=101)

## Decision Tree Classification
### Without Standardization

## Training & Predicting

In [14]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [15]:
predictions = classifier.predict(X_test)

### Performance Evaluation

In [16]:
from sklearn.metrics import confusion_matrix
# Confusion Matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[2671,  110],
       [ 109,  560]])

In [16]:
# Accuracy = TP + TN / TP + TN + FN + FP
accuracy = (cm[0][0] + cm[1][1]) / (cm[0][0] + cm [0][1] + cm [1][0] + cm[1][1])
# Accuracy
accuracy * 100

93.65217391304348

In [17]:
from sklearn.metrics import classification_report
target_names = ['Seizure Activity', 'Non Seizure Activity ']
print(classification_report(y_test, predictions, target_names=target_names))

                       precision    recall  f1-score   support

     Seizure Activity       0.96      0.96      0.96      2781
Non Seizure Activity        0.84      0.84      0.84       669

          avg / total       0.94      0.94      0.94      3450



## Using random forest

In [18]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

/home/maddy/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [19]:
rfc_pred = rfc.predict(X_test)

### Performance Evaluation

In [20]:
cm = confusion_matrix(y_test, rfc_pred)
cm

array([[2746,   35],
       [  45,  624]])

In [21]:
# Accuracy = TP + TN / TP + TN + FN + FP
accuracy = (cm[0][0] + cm[1][1]) / (cm[0][0] + cm [0][1] + cm [1][0] + cm[1][1])
# Accuracy
accuracy * 100

97.68115942028986

In [22]:
target_names = ['Seizure Activity', 'Non Seizure Activity ']
print(classification_report(y_test, predictions, target_names=target_names))

                       precision    recall  f1-score   support

     Seizure Activity       0.96      0.96      0.96      2781
Non Seizure Activity        0.84      0.84      0.84       669

          avg / total       0.94      0.94      0.94      3450



# Decision Tree Classification
### With Standardization

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [24]:
scaler.fit(eeg_data.drop('y',axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [25]:
scaled_features = scaler.transform(eeg_data.drop('y',axis=1))

In [26]:
eeg_feature = pd.DataFrame(scaled_features)
eeg_feature.head(3)

0         1         2         3         4         5         6    \
0  0.885051  1.209929  1.462764  1.439539  1.242366  0.818262  0.380910   
1  2.400577  2.366190  2.239441  2.109257  2.037441  1.996033  1.941660   
2 -0.123287 -0.169154 -0.225131 -0.172743 -0.149016 -0.179743 -0.312756   

        7         8         9      ...          168      169       170  \
0 -0.014267 -0.163196 -0.198415    ...     0.105907 -0.04163 -0.020282   
1  1.719102  1.546403  1.484569    ...     1.074264  1.05770  0.972841   
2 -0.409056 -0.484131 -0.547478    ...     0.233004  0.40782  0.455214   

        171       172       173       174       175       176       177  
0 -0.107131 -0.375743 -0.535944 -0.693858 -0.634144 -0.433290 -0.235399  
1  0.943023  0.982911  1.018615  1.029295  1.023429  0.954241  0.856537  
2  0.361582  0.193824  0.008151 -0.103237 -0.136872 -0.138593 -0.144405  

[3 rows x 178 columns]

### Train Test Split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(eeg_feature,eeg_data['y'],
                                                    test_size=0.30)

## Training and Predicting & Evaluation

In [28]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [29]:
predictions = classifier.predict(X_test)

In [30]:
# Confusion Matrix
cm = confusion_matrix(y_test, predictions)
cm

array([[2649,  108],
       [ 115,  578]])

In [31]:
# Accuracy = TP + TN / TP + TN + FN + FP
accuracy = (cm[0][0] + cm[1][1]) / (cm[0][0] + cm [0][1] + cm [1][0] + cm[1][1])
# Accuracy
accuracy * 100

93.53623188405797

In [32]:
from sklearn.metrics import classification_report
target_names = ['Seizure Activity', 'Non Seizure Activity ']
print(classification_report(y_test, predictions, target_names=target_names))

                       precision    recall  f1-score   support

     Seizure Activity       0.96      0.96      0.96      2757
Non Seizure Activity        0.84      0.83      0.84       693

          avg / total       0.94      0.94      0.94      3450



# Random Forest Classification
### With Standardization

In [33]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=100)
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [34]:
rfc_pred = rfc.predict(X_test)

In [35]:
cm = confusion_matrix(y_test, rfc_pred)
cm

array([[2724,   33],
       [  41,  652]])

In [36]:
# Accuracy = TP + TN / TP + TN + FN + FP
accuracy = (cm[0][0] + cm[1][1]) / (cm[0][0] + cm [0][1] + cm [1][0] + cm[1][1])
# Accuracy
accuracy * 100

97.85507246376811

In [37]:
target_names = ['Seizure Activity', 'Non Seizure Activity ']
print(classification_report(y_test, predictions, target_names=target_names))

                       precision    recall  f1-score   support

     Seizure Activity       0.96      0.96      0.96      2757
Non Seizure Activity        0.84      0.83      0.84       693

          avg / total       0.94      0.94      0.94      3450

